name: Build Pacman Packages

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Instalar dependências
        run: |
          pacman -Syu --noconfirm base-devel git

      - name: Verificar pacotes do PR alterados e compilar
        if: github.event_name == 'pull_request'
        run: |
          mkdir -p repo
          cd packages

          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^packages/' | cut -d/ -f2 | sort -u)

          for dir in $CHANGED_DIRS; do
            cd "$dir"
            pkgname=$(source PKGBUILD && echo $pkgname)
            pkgver=$(source PKGBUILD && echo $pkgver)
            pkgrel=$(source PKGBUILD && echo $pkgrel)
            arch=$(source PKGBUILD && echo ${arch[0]})
            output_file="../../repo/${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst"

            if [[ ! -f "$output_file" ]]; then
              echo "Compilando $pkgname..."
              makepkg -s --noconfirm --clean --cleanbuild
              cp *.pkg.tar.zst ../../repo/
            fi
            cd ..
          done
          cd ..
      - name: Verificar pacotes do dispacth
        if: github.event_name == 'workflow_dispatch'
        run: |
          rm -rf repo
          mkdir -p repo
          cd packages

          for dir in */; do
            cd "$dir"
            if [[ -f PKGBUILD ]]; then
              echo "Compilando $pkgname..."
              makepkg -sf --noconfirm --clean --cleanbuild
              cp *.pkg.tar.zst ../../repo/
            fi
            cd ..
          done
          cd ..

      - name: Atualizar banco de pacotes
        run: |
          cd repo
          repo-add -n -R orion.db.tar.gz *.pkg.tar.zst

      - name: Commit e Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add repo/*.pkg.tar.zst
          git add repo/*.db* repo/*.files*
          git commit -m "Atualiza repositório com novos pacotes" || echo "Nada para commitar"
          git push
